### ISSUE TITLE
Error on `lando setup` Docker Desktop Install: Enquirer is a peer dependency that must be installed separately.

### ISSUE THREAD

**Issue by reynoldsalec** [lando/core#105]
Reported by @tormi:

I’m having issues with lando setup tool in latest stable v3.21 beta. I uninstalled Docket Desktop before running it to test it out. Failed to install DD, here is the error message (I’m on Mac M1):

`Enquirer is a peer dependency that must be installed separately.`

![image](https://github.com/lando/core/assets/1153738/2877f2e3-b48a-4779-8d6f-d50cf9a387c3)

**Comment by reynoldsalec** [comment]
This is some sort of issue with `listr2`; this thread seems to have some promising clues: https://github.com/listr2/listr2/issues/631

It's possible that, even though we're running a version of `listr2` that has the fix applied and our installed version of `enquirer` seems to be appropriate, we may need to do something like this to get it to work: https://github.com/patrickm68/NodeJS-core-utils/commit/6b8d56de9c99d86d8be0ee744dd8c69300f752f8#diff-824ae9859443ce81f838da1cd72c7947afebf778176baad72f40d41f4fc102feR26-R28

**Comment by pirog** [comment]
tracked this down but in the meantime you can workaround this by manually installing `@lando/core` with `lando plugin-add @lando/core`

**Comment by pirog** [comment]
alright this should be deployed in the latest core 3.21.0-beta.2 which you can get with `lando update`

**Comment by soleneggd** [comment]
Well I had the same issue, but since I made `lando update`, I can't start lando anymore. When it tries to start docker, it asks me to "Enter computer password for [user] to start docker". But when I type my user password, it doesn't work and the question is still here. I tried to change my password, but same issue...
