### ISSUE TITLE
`lando setup` crashes when WSL is not installed on Windows

### ISSUE THREAD

**Issue by AaronFeledy** [lando/core#117]
When running `lando setup` on a Windows machine that does not have WSL installed, setup crashes with a `wsl ENOENT` error.

**Comment by pirog** [comment]
ahh interesting. when i tested this i removed all relevant apps/features but apparently that does not remove `wsl.exe` which i must have took to mean it was available on windows by default.

**Comment by pirog** [comment]
ok so this is a deeper issue cause by `run-command.js` not handling cases where `command` does not exist.

**Comment by pirog** [comment]
alright ive got a PR on this: https://github.com/lando/core/pull/124 going to try to get #116 and #118 in there as well before i merge
