### ISSUE TITLE
Lando setup produces an exit code of 0 when there are errors

### ISSUE THREAD

**Issue by AaronFeledy** [lando/core#118]
When running `lando setup` and encountering errors such as #116 and #117, Lando does not throw an error code. This is problematic if `lando setup` is being executed by a script that needs to identify whether setup was successful.

**Comment by pirog** [comment]
@AaronFeledy do you think this is exclusive to windows?

**Comment by pirog** [comment]
Adding some more context here. At least on my mac the following conditions produced an exit code of 1

* Attempting to download a bogus plugin eg 404
* Attempting to download a bogus orchestrator eg 404
* Attempting to download a bogus build engine eg 404
* Throwing an error directly in a setup task
* Attempting a bogus command in `install-docker-desktop.sh`

@AaronFeledy what part of setup is failing for you? Will try a few things out in Windows but suspect that maybe the powershell script is not bubbling up its error?

**Comment by pirog** [comment]
@AaronFeledy i tried a lot of different combinations to try and replicate this but could not. How sure are you? Can you provide concrete steps to replicate? I pushed up a generic `trap` for the Docker Desktop installer script which _feels_ like the place most susceptible to this. 

I'll keep this issue open for now but im at "cannot replicate" and moving onto other things.

**Comment by AaronFeledy** [comment]
The generic `trap` seems to have done the trick. Docker Desktop install was throwing an exception in an environment with an incomplete WMI repository.
