### ISSUE TITLE
Custom plugins aren't detected since v3.21

### ISSUE THREAD

**Issue by drubb** [lando/core#127]
After upgrading to v3.21, I'm facing the following kind of error messages:
```
ERROR ==> Could not find a plugin in /home/myuser/projects/myproject/.lando/plugins/my-plugin
```
As far as I can see from the code, it's no longer sufficient to provide an index.js for the plugin, meanwhile also a package.json is required, otherwise this error will be thrown.

If this is an intentional change, it should be documented somewhere.

The culprit lines from components/plugins.js:

```
// throw error if plugin does not seem to exist
    if (!fs.existsSync(path.join(this.root, 'package.json'))) throw new Error(`Could not find a plugin in ${this.root}`); // eslint-disable-line max-len

    // set top level things
    this.location = this.root;
    this.pjson = read(path.join(this.root, 'package.json'));
    this.sourceRoot = this.root;
```
Maybe it was meant to be 'index.js', not 'package.json'?

**Comment by pirog** [comment]
The new plugin detection backports the `plugin` spec from lando 4 which has a stricter and more well-defined idea around what constitutes a plugin and is definitely different than lando 3. 

I think, ideally, we should accommodate the older lando 3 requirements eg "it has an index.js" but throw a warning that its deprecated and should be updated to the new spec with a link to a guide to do that. 

Let me investigate and see if that is easily doable and ill get back to you. In the meantime anyone who ends up here can work around the issue by satisfying the minimal requirements for lando 4 plugin identification 

1. create a minimal `package.json` with a `lando` key eg

```json
{
  "name": "my-plugin",
  "keywords": [
    "lando-plugin"
  ],
  "lando": {}
}
```

2. create a minimal `plugin.yml` 
```yaml
name: my-plugin
```

both should live side by side in the root of your plugin.
