### ISSUE TITLE
`channel: stable` is being ignored

### ISSUE THREAD

**Issue by crstauf** [lando/core#133]
Even with `channel: stable` in `~/.lando/config.yml`, I constantly see the nag about a beta release being available. The project's Lando config does not have a `channel` property. Why is global config being ignored?

**Comment by reynoldsalec** [comment]
@crstauf apologies for the confusion, you can read my bigger explanation on this over here: https://github.com/lando/lando/issues/3666#issuecomment-1953213246

Going to close this out but definitely feel free to continue the convo here or ping me on Slack.

**Comment by crstauf** [comment]
Thanks, @reynoldsalec.
