### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by sinnbeck** [lando/core#175]
I am getting ready to install the newest version of Lando after it was changed to require an installer instead of manually installing a deb file. Now I cannot seem to find a way to uninstall it again in case something goes wrong and I need to roll back to the deb version?

https://docs.lando.dev/install/linux.html

Is there a secret page that explains the uninstall process?

**Comment by AaronFeledy** [comment]
Everything is in `~/.lando`. You can just delete that directory then install the deb package.

**Comment by sinnbeck** [comment]
Oh. I thought it added files to /usr/local/bin as well?

From the install script
```bash
DEST="${LANDO_INSTALLER_DEST:-/usr/local/bin}"
```

**Comment by AaronFeledy** [comment]
Oh, my mistake. I believe the plan was to put everything in ~/.lando but that doesn't seem to have happened in the bash installer.

**Comment by pirog** [comment]
https://docs.lando.dev/getting-started/uninstalling.html

**Comment by sinnbeck** [comment]
@pirog Brilliant thanks!
