### ISSUE TITLE
`ERROR ==> Cannot detect connection to internet!` when running certain `lando` commands

### ISSUE THREAD

**Issue by rhendrickson-sc** [lando/core#213]
After running `lando update` yesterday (September 25, 2024), I am no longer able to run two `lando` commands because Lando throws an error and says it cannot detect a connection to the internet. The two commands in question are `lando start` and `lando update`.

The output of `lando start` is the following:
![image](https://github.com/user-attachments/assets/ccecc613-1ec4-42be-99bd-148104e0a1ee)

The output of `lando update` is the following:
![image](https://github.com/user-attachments/assets/aae35804-fe3e-4c5c-90f4-55e0f12af5d9)

I can provide a more verbose output of either command if needed.

I tried reinstalling Lando (2 attempts, 1 with keeping the `~/.lando` directory, and the other I removed that directory) but the issue persists.

System information:
OS: Windows 11 Pro
WSL version: 2.2.4.0
WSL distro: Ubuntu 24.04.1
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22621.4169

**Comment by rhendrickson-sc** [comment]
To anyone else who finds themselves in this situation: after a lot of troubleshooting with the Lando devs in Slack, it was determined that the fix would be [resetting the Ubuntu instance of WSL](https://devwithlando.slack.com/archives/C2XBSHX8R/p1727387648410989?thread_ts=1727377034.224769&cid=C2XBSHX8R).

**Comment by reynoldsalec** [comment]
Thanks for following up on this @rhendrickson-sc, ok to close this out?

**Comment by rhendrickson-sc** [comment]
@reynoldsalec Yeah! Thanks for double checking!
