### ISSUE TITLE
the v3.22.3 release don't contains the lando-* installer files

### ISSUE THREAD

**Issue by dmouse** [lando/core#237]
Hi,

I just realized that files like `lando-linux-arm64` are not included in the new release. Is this a bug or was it intentional?

https://github.com/lando/core/releases/tag/v3.22.3

Thanks

**Comment by AaronFeledy** [comment]
The publishing of the release on github kicks off a bunch of automated testing and building processes that end in the uploading and attaching of the binaries to that release as each build completes, which takes some time. Looks like you were just a bit faster than the robots today!
