### ISSUE TITLE
ERROR ==> Cannot detect connection to internet!

### ISSUE THREAD

**Issue by zdenekgebauer** [lando/core#243]
Approximately from version 3.22.1 with Docker Desktop 4.34.3 on Win10 the message appears irregularly  
```ERROR ==> Cannot detect connection to internet!```
It appears at various stages of  ```lando start``` and ```rebuild```, in multiple configuratins (LAMP recipe based)  with different databases (mysql, mariadb) and different versions of php. This is not a problem with the host's internet connection.  

Downgrade to DockerDestop 4.34.0 did not help.  What exactly does this message mean and how to more accurately diagnose the cause of the problem?

**Comment by reynoldsalec** [comment]
Are you using WSL2? This earlier issue might be relevant: https://github.com/lando/core/issues/213#issuecomment-2379439162

**Comment by zdenekgebauer** [comment]
resetting WSL did not help , still getting 
```
lando start -vv
.......
  lando ERROR Error: Cannot detect connection to internet!
    at C:\snapshot\cli\node_modules\@lando\core\lib\updates.js  +15014ms
```

**Comment by pirog** [comment]
we are going to modify these checks to be a bit more specific, should be different in the next release although that is not a guarantee that it will work!

**Comment by zdenekgebauer** [comment]
I'm sure problem is caused by WSL2, because docker shows errors like this one https://forums.docker.com/t/docker-desktop-is-not-working-on-windows-11/141491 .
Reset and reinstall WSL2 did not help, so my temporary workaround is uninstall Docker desktop and install again with unchecked option "use WSL2".
