### ISSUE TITLE
`lando update` always shows lando/cli as update available

### ISSUE THREAD

**Issue by justclint** [lando/core#259]
Not sure if this issue belongs here or in lando/lando repo but just thought Id start here. 

Lando version: v3.21.0-beta.18

When running `lando update` and completing update, lando/cli still shows as needs to update. Ive tried updating many times but it just always says update available.

Ive included a screenshot to illustrate.

<img width="749" alt="Screenshot 2024-05-02 at 9 28 07 AM" src="https://github.com/lando/core/assets/466984/1301e699-c1d3-4598-af7e-28bef77b88a4">

**Comment by uberhacker** [comment]
I can confirm this happens with `v3.21.0-beta.18` too.

**Comment by square360-george** [comment]
Same here. It gets to 100% download, but never completes the install (checkmark missing)

![CleanShot 2024-05-07 at 15 20 07@2x](https://github.com/lando/cli/assets/5714213/4f876c05-7ec8-4c07-9ea1-f12c27a52f4a)

**Comment by pirog** [comment]
If this is happening its because you aren't actually running the correct CLI likely because an older version of `lando` is ahead in your `PATH`. Try the following stuff to verify

start by opening a new terminal.

```sh
# which lando is running
which lando

# this should report the "older" version eg not beta.18
lando version --component @lando/cli

# remove the older lando
sudo rm -rf /path/from/which/lando

# verify the new one is being used
which lando
lando version --component @lando/cli
```

If that all works you should be good. For more detail: https://docs.lando.dev/cli/guides/adding-lando-2-path.html

**Comment by square360-george** [comment]
Thanks. This started me on the correct path to fix. Turns out it was not a path issue. The permissions on the cache for the files in the `/Users/person/Library/Caches/lando` directory were somehow messed up. I deleted all files in that directory, and the latest @lando/cli installed without issue.

**Comment by justclint** [comment]
Thanks, after removing older path to lando `/usr/local/bin/lando`, then reinstalling, which now is in `/User/myusername/.lando/bin/lando`, the cli updated successfully and now on beta.20.

**Comment by GeoJunkie** [comment]
This happened to me when updating to the release `v3.21.0` version cli. It looks like it may have considered `v3.21.0` to be older than `v3.21.0-beta.6`.

 I used the [cached version mentioned here ](https://github.com/lando/core/issues/259) by running this from inside my home folder: `cp Library/Caches/lando/v3.21.0/bin/lando /usr/local/bin/`.

This copied the downloaded version over to my path folder and then `lando version --component @lando/cli` showed the correct, updated version.

**Comment by justclint** [comment]
Ran into this again when trying to update cli to v3.21.0 from v3.21.0-beta. 

Only solution that seems to work for me is to just reinstall lando.

`/bin/bash -c "$(curl -fsSL https://get.lando.dev/setup-lando.sh)"`

**Comment by reynoldsalec** [comment]
In most cases, this should be resolved by Pirog's comment in https://github.com/lando/core/issues/259#issuecomment-2445065855

Going to close out, but if you're facing this issue and those guidelines don't work for you, feel free to comment here or (preferably) to reach out on the Lando Slack ([link to join](https://www.launchpass.com/devwithlando)).

**Comment by danyg79** [comment]
Just a quick note, [justclint](https://github.com/justclint)'s suggestion to reinstall Lando was the only solution for me when I was facing the same issue.
