### ISSUE TITLE
Install fails with error EPERM: operation not permitted, mkdir '.ssh' EPERM

### ISSUE THREAD

**Issue by misterjoonas** [lando/core#282]
I have not been running lando in a long time and it started to complain that I need to run `lando setup`. Running the command complained about the same thing. Then I tried to do `lando update`. And after that I just tried to re-install everything with the setup script.

```
❯ /bin/bash -c "$(curl -fsSL https://get.lando.dev/setup-lando.sh)" --debug
this script is about to:

- download lando v3.23.14-slim to /Users/joonasmerilainen/.lando/bin
- run lando setup
- run lando shellenv --add

Press RETURN/ENTER to continue or any other key to abort:
downloading https://github.com/lando/core/releases/download/v3.23.14/lando-macos-arm64-v3.23.14-slim to /Users/joonasmerilainen/.lando/bin/lando
################################################################################################################################################################################################ 100.0%
ERROR ==> EPERM: operation not permitted, mkdir '.ssh' EPERM
ERROR: Failed during: /var/folders/pt/8n5g_dn55qsfrn86cyqp6zl00000gn/T//12492 version
```

I have not found any advice anywhere and nobody else at the company has this problem, so this might be some issue in my machine. I had the problem earlier in macOS Sonoma but it persists in macOS Sequoia too. I really hope I don't need to re-install clean macOS because of lando. Have not had any problems with any other applications and DDEV works fine with Docker desktop.

**Comment by pirog** [comment]
@misterjoonas i would look at the permissions in `~` and make sure everything in there is owned by you, especially `.ssh`. Force removing all of `~/.lando` is not a bad idea if you are getting permission errors there as well. `sudo rm -rf ~/.lando`

If you want to curl the script and run with debug you need to do this 

```sh
LANDO_INSTALLER_DEBUG=1 /bin/bash -c "$(curl -fsSL https://get.lando.dev/setup-lando.sh)"
```

**Comment by misterjoonas** [comment]
Thanks, I realized it myself when I downloaded the script and ran it with `--debug` switch, I saw the install directory to be `~/.lando`. After removing the directory completely the setup worked fine. I don't know why it was complaining about the `~/.ssh` directory, maybe because an extra attribute is added there for docker? 🤷 
```
❯ xattr ~/.ssh
com.apple.provenance
com.docker.grpcfuse.ownership
```
