### ISSUE TITLE
invalid PATH env after Lando install

### ISSUE THREAD

**Issue by leapxdco** [lando/core#298]
After installing, My path was updated to:

```bash
# Lando
export PATH="/Users/me/.lando/bin${PATH+:$PATH}"; #landopath
```

I manually corrected to :

```bash
# Lando
export PATH="/Users/me/.lando/bin:$PATH"; #landopath
```

This fixed my issues

Version: 3.23.7
OS: OSX Ventura 13.5 (22G74)
Terminal: ZSH 5.9
rcfile: .zshrc

**Comment by pirog** [comment]
hmmm not sure why `export PATH="/Users/me/.lando/bin${PATH+:$PATH}"; #landopath` wouldn't work. im running more or less the same as you. 

that said maybe `${PATH+:$PATH}` is too clever and we should just do the simple thing.
