### ISSUE TITLE
New URL scanner returns fail for redirects?

### ISSUE THREAD

**Issue by Stargate-project** [lando/core#35]
URLs never work anymore, they initially work sometimes on new projects but as soon as more projects are added something gets update

```
    ✖ https://localhost:53166 [301] - REQUEST FAILED WITH STATUS CODE 301
    ✖ http://localhost:53167 [301] - REQUEST FAILED WITH STATUS CODE 301
```

**Comment by pirog** [comment]
@Stargate-project the new URL scanner is experimental so we are still working on getting its behavior correct. I would check out the docs here https://docs.lando.dev/core/v3/scanner.html

Your best options are to either revert back to the "legacy scanner" 
https://docs.lando.dev/core/v3/scanner.html#using-the-legacy-scanner

Or make use of the new configuration options
https://docs.lando.dev/core/v3/scanner.html#adding-ok-codes
in your case you probably want to either choose a path that works or add 301 to the list of OK codes

I'm going to rename this issue to scope it around redirects specifically.
